<?php

namespace Faculte\AdminBundle\Repository;

/**
 * AbsenceEtdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceEtdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroupeAndMatiere($idMatiere,$idGroupe){
           $query = $this->createQueryBuilder('ab_etd')
               ->select('ab_etd')
               ->leftJoin('ab_etd.matiere', 'matiere')
               ->leftJoin('ab_etd.formation', 'formation_etd')
               ->leftJoin('formation_etd.groupe', 'groupe')
               ->leftJoin('formation_etd.etudiant', 'etudiant')
               ->where('groupe.id = :IdGroupe')
               ->andWhere('matiere.id = :IdMatiere')
               ->setParameters(array('IdGroupe'=>$idGroupe,'IdMatiere'=>$idMatiere))
               ->getQuery()
               ->getResult();
        return $query;
    }

    public function findByFormationAndMatiere($idMatiere,$idFormation){
        $query = $this->createQueryBuilder('ab_etd')
            ->select('ab_etd')
            ->leftJoin('ab_etd.matiere', 'table_matiere')
            ->leftJoin('ab_etd.formation', 'formation_etd')
            ->leftJoin('formation_etd.etudiant', 'etudiant')
            ->where('table_matiere.id = :idMatiere')
            ->andWhere('formation_etd.id = :idFormation')
            ->setParameters(array('idFormation'=>$idFormation,'idMatiere'=>$idMatiere))
            ->getQuery()
            ->getOneOrNullResult();
        return $query;
    }
}
