<?php

namespace Faculte\AdminBundle\Repository;

/**
 * CommentaireInscriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireInscriRepository extends \Doctrine\ORM\EntityRepository
{
}
