<?php

namespace Faculte\AdminBundle\Repository;

/**
 * DemandeRattrapageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRattrapageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMaxNonConsulter($max){
        $query = $this->createQueryBuilder('demande')
            ->select('demande')
            ->where('demande.consulter = 0')
            ->setMaxResults($max)
             ->getQuery()
            ->getResult();
        return $query;
    }
}
