<?php

namespace Faculte\AdminBundle\Repository;

/**
 * EmploiTempsEnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiTempsEnseignantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idETEn){
        $query = $this->createQueryBuilder('emploi_tmp')
            ->select('emploi_tmp')
            ->where('emploi_tmp.id != :idETEn')
            ->setParameters(array('idETEn'=>$idETEn))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
