<?php

namespace Faculte\AdminBundle\Repository;

/**
 * EmploiTempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiTempsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idET){
        $query = $this->createQueryBuilder('emploi_tmp')
            ->select('emploi_tmp')
            ->where('emploi_tmp.id != :idET')
            ->setParameters(array('idET'=>$idET))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
