<?php

namespace Faculte\AdminBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
