<?php

namespace Faculte\AdminBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository

{
    public function findWithoutId($idFO){
        $query = $this->createQueryBuilder('formation')
            ->select('formation')
            ->where('formation.id != :idFO')
            ->setParameters(array('idFO'=>$idFO))
            ->getQuery()
            ->getResult();
        return $query;
    }

}
