<?php

namespace Faculte\AdminBundle\Repository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMaxNonConsulter($max){
        $query = $this->createQueryBuilder('ListeInscriptions')
            ->select('ListeInscriptions')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
        return $query;
    }
}
