<?php

namespace Faculte\AdminBundle\Repository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idN){
        $query = $this->createQueryBuilder('niveau')
            ->select('niveau')
            ->where('niveau.id != :idN')
            ->setParameters(array('idN'=>$idN))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
