<?php

namespace Faculte\AdminBundle\Repository;

/**
 * ParticulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticulierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idPR){
        $query = $this->createQueryBuilder('particulier')
            ->select('particulier')
            ->where('particulier.id != :idPR')
            ->setParameters(array('idPR'=>$idPR))
            ->getQuery()
            ->getResult();
        return $query;
    }

}
