<?php

namespace Faculte\AdminBundle\Repository;

/**
 * ProfessionelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($id){
        $query = $this->createQueryBuilder('professionel')
            ->select('professionel')
            ->where('professionel.id != :id')
            ->setParameters(array('id'=>$id))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
