<?php

namespace Faculte\AdminBundle\Repository;

/**
 * PublierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idP){
        $query = $this->createQueryBuilder('publier')
            ->select('publier')
            ->where('publier.id != :idP')
            ->setParameters(array('idP'=>$idP))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
