<?php

namespace Faculte\AdminBundle\Repository;

/**
 * ResultatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithoutId($idR){
        $query = $this->createQueryBuilder('resultat')
            ->select('resultat')
            ->where('resultat.id != :idR')
            ->setParameters(array('idR'=>$idR))
            ->getQuery()
            ->getResult();
        return $query;
    }
}
